AWSTemplateFormatVersion: '2010-09-09'
Description: 'lambda_layer_demo

  Sample SAM Template for lambda_layer_demo

  '
Globals:
  Function:
    Timeout: 60
Outputs:
  MyLambdaLayerARN:
    Description: ARN of MyLambdaLayer function
    Export:
      Name: mylambda-layer-arn
    Value:
      Ref: MyLambdaLayer
Resources:
  DeserializeDemoFunction:
    Properties:
      CodeUri: s3://layer1stfeb/695843da5eb76331e30d1b05f25f5d25
      Description: This function is for deserialize demo
      FunctionName: LayerApp-deserialize-demo
      Handler: main.lambda_handler
      Layers:
      - Ref: MyLambdaLayer
      Role: arn:aws:iam::752369343347:role/service-role/LayerDemoRole
      Runtime: python3.7
    Type: AWS::Serverless::Function
  MyLambdaLayer:
    Properties:
      CompatibleRuntimes:
      - python3.6
      - python3.7
      ContentUri: s3://layer1stfeb/706016597da0366a7485fa109490d8e5
      Description: This layer include objectpath dependency and json data
      LayerName: MyLambdaLayer
      LicenseInfo: MIT
      RetentionPolicy: Retain
    Type: AWS::Serverless::LayerVersion
  ObjectpathDataDemoFunction:
    Properties:
      CodeUri: s3://layer1stfeb/960e963888d70122627fc1150b8f2920
      Description: This function is for objectpath-data-demo
      FunctionName: LayerApp-objectpath-data-demo
      Handler: main.lambda_handler
      Layers:
      - Ref: MyLambdaLayer
      Role: arn:aws:iam::752369343347:role/service-role/LayerDemoRole
      Runtime: python3.7
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
